### PR TITLE
Fix for missing conversation messages

### PR DESCRIPTION
**Pull request by watsonbox**
Previous logic produces incomplete conversations, since some messages have no dialog_partner. New approach is based on the assumption that only one conversation exists with exactly two participants (true for the databases I have seen), for each dialog partner. The complete conversation is therefore all messages associated with that conversation.

I am using Skype 6.19 (452) on OSX 10.9.5.

### CODE REVIEW

**Comment by Temptin** [comment]
@watsonbox Thank you very much for finding this issue and tracking it down! The new query statement is pretty well-made; and you are correct that there is only one convo_id per "real" skype partner (only conferences have multiple ones), and your idea of finding convo_ids where participant count is exactly 2 (meaning you and someone else) is clever, since conferences should _almost certainly_ only be able to be 3 or more since they're started by adding a 3rd person to a regular chat, which in turn creates a new convo_id with 3 people in it.

The root of this is yet again a bug in Skype 6+ which causes them to sometimes save a NULL value to the database instead of the real dialog_partner value. It has nothing to do with your theory about online-status etc; it's totally random. The Skype programmers are incompetent and this kind of random inconsistency is the kind of thing I dealt with 8 hours a day for 3 weeks straight during the initial reverse engineering. And I know it was introduced in Skype 6+ because I had a Skype 4/5 database with years of conversations back then, and it never had a NULL value for dialog_partner.

However, I don't know if I am going to use the provided code... definitely not as-is; because we have to think about this further: You're changing a dialog_partner search to a convo_id search, which _also_ breaks due to _another_ bug in their database.

You know that massive comment in skypeparser_parsing.cpp with a full description of all database field names and their meanings? Well, it will explain further why we should NOT use convo_id to find all messages:

_"convo_id (integer): this is the unique identifier for your dialog partner combination; it is permanent (the same whenever you talk to the same partner). also, whenever you create a conference chat (more than 2 people), it generates a new convo_id. The "Conversations" table contains mappings for id -> partner's "identity" (skypeID) and other info. we'll mainly be using convo_id to correlate calls in the Calls table. LONG NOTE: However, you should NOT use convo_id to "locate all events between you and that person"; use dialog_partner for that, because otherwise you will be lacking some events, primarily (or only? it is the only missing one I have observed) event type 10 aka the creation of a new group conference chat (by inviting more chat partners), as that event will still have a dialog_partner that's the same as the person you were chatting with, but the convo_id will be new (the new convo id for that new group conference, to be precise) - note that this is useful info if you want to parse group convos too, simply store all eventtype 10 convo ids and then parse those too; the first event of a group conference has the dialog_partner you were with when the group conference was started, and the remaining ones have a null value for dialog_partner."_

I am going to continue investigating and have some ideas for solutions; for instance, I might simply change it to dialog_partner OR convo_id.

In other news; please delete your fork and re-clone it since I've transferred the project and refactored the entire history and began work again under my new Github account, so your "origin" remote and history is all outta whack. ;-) Alternatively, check "git remote -v" to make sure both upstream remotes say "https://Temptin@github.com/Temptin/SkypeExport.git" and do a full, clean pull that overwrites your old history, and then do a force push to _your own_ GitHub fork with something like "git push -u --force origin master".

I've got the new statement and will be merging it manually when a complete fix is found, so don't worry about the pull request.

**Comment by Temptin** [comment]
Further testing is turning out well. Your code was indeed picking up a few missing messages caused by the Skype 6+ dialog_partner bug; but was missing conference creation (as explained in the quoted comment above), and was mis-ordering _every_ event that had identical timestamps. Events in the database are only stored by their full second of transmission/receiving, so it's not uncommon to type at exactly the same time. That is why it's very important to extract events in the exact order they were added to the database, and _then_ order by timestamp a 2nd time just to make sure it's all correct.

When merging my previous dialog_partner statement with your table join using an OR, it tries to FIRST find them by dialog_partner, and THEN picks up any "buggy stragglers" using your nice table join method. This means your table join never has a chance to re-order the events with identical timestamp, since they've already been picked up by dialog_partner. It also means we retain the conference creation events (described earlier).

So the best of both worlds is almost here now; just a bit more testing, then you can expect to see a new commit. ;-)

**Comment by Temptin** [comment]
Well, I was ready to commit but scanned through the code and found a new bug introduced by this fix: If we're encountering a "conference created" event and we're in 1on1 chat parsing mode, we used to only scan by dialog_partner and therefore did the following assumption: _"if we see this event and isConference is false then it MEANS _WE_ created it, because that is the ONLY time a type10 event occurs with a dialog_partner of the person you're talking to."_

I'll have to change that code a bit as well to un-break the detection of conference start-events, otherwise all exported histories from now on will say that we created the conference even when they did it.

**Comment by Temptin** [comment]
Damnit... The issues go deeper than that. Skype 6+ has changed how conference creation (type 10) events are stored; they're now instantly written to the new convo_id instead of the old 1on1 convo_id. I'll redo the whole conference scanning code by adding "OR type=10" and loads more code to figure out the direction. Turns out this was not easy to fix, but the idea I've got should be backwards compatible too, which is good.

**Comment by Temptin** [comment]
@watsonbox Took a few hours but this has now been fixed using a much more complex yet fully stable and backwards-compatible method. I didn't end up using any of your code, but thank you for reporting the bug. Full details are in the commit if you are curious:
https://github.com/Temptin/SkypeExport/commit/956879429a079f2aecedb7ec5d4c68217184bd0a

There have also been a boatload of other commits to improve the general project, see here:
https://github.com/Temptin/SkypeExport/commits/master

Now all that remains for you is to delete your fork and re-clone it using the latest codebase, as I mentioned earlier.

**And to celebrate all of those changes and the fact that the project has proven its stability, it's time to pop the big 1.0!**

https://github.com/Temptin/SkypeExport/releases/latest

You'll definitely want to re-export your history using this new version to take advantage of all the improvements. You will find binaries and a release summary at the above link. Enjoy!

**Comment by watsonbox** [comment]
@Temptin Awesome thanks a lot for all this work.  I'll take a closer look at this ASAP and re-export my Skype data etc.

**Comment by Temptin** [comment]
@watsonbox Ah there you are, the man is alive at last! ;-)

There are more changes coming and v1.1 is not far off, probably today or tomorrow, so wait with your re-exports until that's done.

In the meantime I suggest deleting your outdated repo, doing a fresh fork, and then pulling the final v1.1 changes as they come in the next few days. There will of course also be v1.1 binaries under the Releases tab of the project.

**Comment by Temptin** [comment]
@watsonbox Version 1.1.0 is now out and ready to export your histories with a whole slew of improvements!

Check the version history here for a short summary of what the two latest releases have brought, compared to the code you used to be running. There's been a lot of work done to bring everything fully up to Skype 7 spec: https://github.com/Temptin/SkypeExport/blob/master/CHANGES.md

You can find v1.1.0 binaries here: https://github.com/Temptin/SkypeExport/releases

Enjoy! ;-)

**Pull request closed without merging**
